export const GET_DATA_REQUEST = "GET_DATA_REQUEST"

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"

export const GET_DATA_FAILURE = "GET_DATA_FAILURE"

export const GET_SEARCH_DATA_REQUEST = "GET_SEARCH_DATA_REQUEST"

export const GET_SEARCH_DATA_SUCCESS = "GET_SEARCH_DATA_SUCCESS"

export const GET_SEARCH_DATA_FAILURE = "GET_SEARCH_DATA_FAILURE"

export const GET_MEDICINE_DATA_REQUEST = "GET_MEDICINE_DATA_REQUEST"

export const GET_MEDICINE_DATA_SUCCESS = "GET_MEDICINE_DATA_SUCCESS"

export const GET_MEDICINE_DATA_FAILURE = "GET_MEDICINE_DATA_FAILURE"



 